In [44]:
# importing basic libraries

import numpy as np

import pandas as pd

from pandas import Series, DataFrame

from sklearn.model_selection import train_test_split

In [46]:
df = pd.read_csv('../dummySet.csv')
df

     a  weight_a    b  weight_b   c  weight_c     d  target
0    1         2    1         3   1         8   234      13
1    4         2    8         3   4         8   234      64
2   10         2   20         3  40         8     1     400
3   20         2    6         3   8         8   123     122
4   60         2   40         3  82         8     2     896
5   50         2   99         3  45         8    34     757
6   97         2   68         3  92         8   534    1134
7   73         2   97         3  99         8  5634    1229
8   38         2   20         3  56         8   534     584
9    8         2   90         3  14         8    23     398
10  29         2    6         3  52         8    23     492
11  33         2   52         3  86         8     3     910
12   8         2   17         3  81         8     4     715
13  17         2    3         3  37         8   325     339
14  82         2   50         3  25         8    34     514
15  46         2   39         3  99         8   645    1001
16  97         2   88         3   8         8    34     522
17  79         2   45         3  28         8   423     517
18  48         2   44         3  63         8     4     732
19  50         2   13         3   9         8   325     211
20  63         2   81         3  68         8   345     913
21   4         2   47         3  36         8    23     437
22  93         2   27         3  77         8   423     883
23  40         2   56         3  65         8   534     768
24  55         2    1         3  16         8   523     241
25  41         2   60         3  50         8   423     662
26  36         2    4         3  42         8     4     420
27  70         2   69         3  26         8   234     555
28   7         2   11         3  37         8    23     343
29  23         2   11         3   6         8    34     127
30  14         2   93         3  15         8   345     427
31  35         2   73         3  83         8    34     953
32  84         2   37         3   2         8   534     295
33  71         2   69         3  86         8  5634    1037
34  50         2   12         3  49         8   654     528
35  45         2    3         3  60         8   534     579
36  38         2   42         3  46         8     5     570
37  70         2   18         3  38         8  4356     498
38  73         2   72         3  98         8    43    1146
39  99         2   26         3  84         8   654     948
40  21         2   99         3  97         8   645    1115
41  36         2   23         3  78         8   534     765
42   9         2  100         3  94         8    45    1070
43  61         2    2         3   6         8     3     176

In [47]:
# select only relevant columns
X = df[['a', 'b', 'c', 'd']]
y = df['target']

In [34]:
# Standardizing the data  OPTIONAL
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
# We need to fit the scaler to our data before transformation
X = scaler.fit_transform(
    X.loc[:])
X

array([[-1.62801621, -1.58159597, -1.50638205],
       [-1.52337541, -1.30400974, -1.41200454],
       [-1.3140938 , -0.82814763, -0.27947447],
       [-0.96529113, -1.38332009, -1.28616787],
       [ 0.42991958, -0.03504411,  1.04181061],
       [-0.86065032, -0.74883728, -1.00303535],
       [ 1.40656707, -0.07469928,  0.75867809],
       [ 0.39503931,  1.31323187,  1.57661647],
       [-0.47696738, -0.07469928, -0.43677032],
       [-0.72112925, -0.94711316, -1.09741286],
       [-0.72112925,  2.18564574, -1.06595369],
       [-0.30256604,  1.47185258,  0.75867809],
       [-0.26768577,  0.2821973 ,  1.48223897],
       [ 1.40656707,  1.2735767 ,  1.13618811],
       [ 0.91824332, -0.66952692, -1.28616787],
       [ 0.01135637, -1.06607868,  1.38786146],
       [ 0.77872225,  0.16323177,  1.04181061],
       [ 0.88336306,  0.48047318,  0.25533139],
       [-1.45361487,  0.48047318, -1.03449452],
       [ 1.19728546, -1.18504421, -1.00303535],
       [ 0.98800386, -0.62987175,  1.29348395],
       [ 0.32527877,  1.94771469,  1.60807564],
       [ 1.09264466,  0.16323177,  0.63284141],
       [ 0.91824332,  1.19426634,  0.79013726],
       [-0.72112925,  0.63909388,  0.22387222],
       [-1.48849514,  0.2821973 ,  0.75867809],
       [ 1.54608814, -0.31263034, -1.47492288],
       [ 0.46479984,  0.40116283,  0.06657638],
       [ 0.04623663,  1.07530082,  0.41262723],
       [-0.89553059, -0.5505614 , -1.03449452],
       [ 1.61584867,  1.67012846,  1.4507798 ],
       [-1.52337541, -1.34366491,  0.56992308],
       [-1.209453  ,  0.440818  , -1.03449452],
       [ 0.29039851, -1.18504421, -0.21655614],
       [-0.19792524,  0.75805941, -0.68844367],
       [-1.27921353,  1.31323187,  0.31824973],
       [-1.27921353, -0.66952692, -0.94011701],
       [ 0.98800386, -0.74883728, -0.02780113],
       [ 1.44144734,  0.12357659,  0.31824973],
       [ 0.84848279, -0.8678028 , -0.81428034],
       [ 0.25551824,  0.48047318, -0.12217863],
       [ 0.11599717, -0.39194069,  1.23056562],
       [ 0.46479984, -1.54194079, -1.34908621]])

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
print("Train")
print(X_train)
print("test")
print(X_test)
print("Y train")
print(y_train)
print("Y test")
print(y_test)

Train
     a    b   c     d
3   20    6   8   123
6   97   68  92   534
27  70   69  26   234
31  35   73  83    34
19  50   13   9   325
17  79   45  28   423
13  17    3  37   325
41  36   23  78   534
15  46   39  99   645
9    8   90  14    23
16  97   88   8    34
30  14   93  15   345
26  36    4  42     4
0    1    1   1   234
29  23   11   6    34
42   9  100  94    45
5   50   99  45    34
11  33   52  86     3
32  84   37   2   534
1    4    8   4   234
39  99   26  84   654
21   4   47  36    23
2   10   20  40     1
33  71   69  86  5634
23  40   56  65   534
35  45    3  60   534
10  29    6  52    23
22  93   27  77   423
18  48   44  63     4
43  61    2   6     3
20  63   81  68   345
7   73   97  99  5634
14  82   50  25    34
28   7   11  37    23
38  73   72  98    43
test
     a   b   c     d
37  70  18  38  4356
24  55   1  16   523
25  41  60  50   423
36  38  42  46     5
34  50  12  49   654
40  21  99  97   645
4   60  40  82     2
12   8  17  81     4
8   38  20  56   534
Y train
3      122
6     1134
27     555
31     953
19     211
17     517
13     339
41     765
15    1001
9      398
16     522
30     427
26     420
0       13
29     127
42    1070
5      757
11     910
32     295
1       64
39     948
21     437
2      400
33    1037
23     768
35     579
10     492
22     883
18     732
43     176
20     913
7     1229
14     514
28     343
38    1146
Name: target, dtype: int64
Y test
37     498
24     241
25     662
36     570
34     528
40    1115
4      896
12     715
8      584
Name: target, dtype: int64

In [49]:
from sklearn.linear_model import LinearRegression

reg = LinearRegression().fit(X_train, y_train)

In [50]:
from sklearn.metrics import mean_absolute_error

y_pred = reg.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
mae

1.4210854715202004e-13

In [51]:
reg.coef_

array([2., 3., 8., 0.])

In [40]:
# We need to fit the scaler to our data before transformation. you have to scale data together with other datasets else you get 0
testInput = scaler.fit_transform([[612312321123, 2, 2342]])
testInput

array([[0., 0., 0.]])

In [53]:
# how to rescale back to the original value
reg.predict(np.array([[61, 2, 6, 2]]))

array([176.])