In [59]:
# importing basic libraries

import numpy as np

import pandas as pd

from pandas import Series, DataFrame

from sklearn.model_selection import train_test_split

In [60]:
df = pd.read_csv('./dummyDataWError.csv')
df

     a  weight_a   b  weight_b   c  weight_c     d  weight_d  target
0    1       100   1        90   1       120   234        33    8032
1    4       100   8        90   4       120   234        33    9322
2   10       100  20        90  40       120     1        33    7633
3   20       100   6        90   8       120   123        33    7559
4   60       100  40        90  82       120     2        33   19506
5   50       100  32        90  87       120    34        33   19442
6   58       100  87        90  85       120   534        33   41452
7   94       100  81        90  41       120   222        33   28936
8   65       100  11        90  53       120    23        33   15302
9    3       100  46        90  49       120    45        33   11079
10  96       100  25        90  29       120    23        33   16089
11  93       100  32        90  56       120     3        33   18999
12  60       100  10        90  49       120     4        33   12912
13  21       100  59        90  49       120   325        33   24015
14  58       100  45        90  90       120    34        33   21772
15  37       100  83        90  33       120    23        33   36415
16  46       100  26        90  18       120    34        33   10222
17  26       100  15        90   6       120   423        33   18629
18  59       100  51        90  37       120     4        33   15062
19  24       100  33        90  85       120   325        33   26295
20  63       100  84        90  29       120   345        33   28725
21  97       100  15        90   7       120    23        33   12649
22  73       100   8        90  93       120   563        33   33139
23  95       100  25        90  38       120   534        33   33932
24  65       100  41        90  54       120   523        33   33929
25  92       100  20        90  77       120   423        33   34199
26  25       100  17        90  91       120     4        33   15082
27  52       100  66        90  43       120   234        33   24022
28  88       100  74        90  91       120  2312        33   27139
29  25       100  26        90  19       120    34        33    8242
30  58       100  16        90  17       120   345        33   20665
31  92       100  88        90   6       120    34        33   18962
32  35       100  38        90  83       120   534        33   34502
33   4       100  88        90  16       120  5634        33  196162
34  24       100  94        90  82       120   654        33   42282
35  19       100  18        90  39       120   534        33   25822
36  14       100  58        90  55       120     5        33   13385
37  67       100  27        90  23       120  4356        33  155638
38  30       100  75        90   5       120    43        33   11769
39  38       100  68        90  42       120   654        33   36542
40  34       100  64        90  86       120   645        33   40765
41  53       100  78        90  58       120   534        33   36902
42  55       100  92        90  77       120    45        33   24505
43  61       100   2        90   6       120     3        33    7099

In [61]:
# select only relevant columns
X = df[['a', 'b', 'c', 'd']]
y = df['target']

In [62]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
print("Train")
print(X_train)
print("test")
print(X_test)
print("Y train")
print(y_train)
print("Y test")
print(y_test)

Train
     a   b   c     d
3   20   6   8   123
6   58  87  85   534
27  52  66  43   234
31  92  88   6    34
19  24  33  85   325
17  26  15   6   423
13  21  59  49   325
41  53  78  58   534
15  37  83  33    23
9    3  46  49    45
16  46  26  18    34
30  58  16  17   345
26  25  17  91     4
0    1   1   1   234
29  25  26  19    34
42  55  92  77    45
5   50  32  87    34
11  93  32  56     3
32  35  38  83   534
1    4   8   4   234
39  38  68  42   654
21  97  15   7    23
2   10  20  40     1
33   4  88  16  5634
23  95  25  38   534
35  19  18  39   534
10  96  25  29    23
22  73   8  93   563
18  59  51  37     4
43  61   2   6     3
20  63  84  29   345
7   94  81  41   222
14  58  45  90    34
28  88  74  91  2312
38  30  75   5    43
test
     a   b   c     d
37  67  27  23  4356
24  65  41  54   523
25  92  20  77   423
36  14  58  55     5
34  24  94  82   654
40  34  64  86   645
4   60  40  82     2
12  60  10  49     4
8   65  11  53    23
Y train
3       7559
6      41452
27     24022
31     18962
19     26295
17     18629
13     24015
41     36902
15     36415
9      11079
16     10222
30     20665
26     15082
0       8032
29      8242
42     24505
5      19442
11     18999
32     34502
1       9322
39     36542
21     12649
2       7633
33    196162
23     33932
35     25822
10     16089
22     33139
18     15062
43      7099
20     28725
7      28936
14     21772
28     27139
38     11769
Name: target, dtype: int64
Y test
37    155638
24     33929
25     34199
36     13385
34     42282
40     40765
4      19506
12     12912
8      15302
Name: target, dtype: int64

In [63]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators = 100,
                           n_jobs = -1,
                           oob_score = True,
                           bootstrap = True,
                           random_state = 42)
rf.fit(X_train, y_train)

RandomForestRegressor(n_jobs=-1, oob_score=True, random_state=42)

In [64]:
rf.feature_importances_

array([0.07516151, 0.17780327, 0.0494409 , 0.69759432])

In [65]:
print(rf.score(X_train, y_train))

0.8659186601020431

In [67]:
rf.predict(np.array([[61, 2, 6, 3]]))

array([9811.97])